# Generated by Django 3.1.7 on 2021-03-19 18:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonsAnalisados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon_user', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, max_length=30), size=6)),
                ('pokemon_troca', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, max_length=30), size=6)),
                ('veredito', models.BooleanField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='PokemonsTrocados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon_user', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, max_length=30), size=6)),
                ('pokemon_troca', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, max_length=30), size=6)),
                ('pokemon_img_user', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, max_length=30), size=6)),
                ('pokemon_base_user', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, max_length=30), size=6)),
                ('pokemon_img_troca', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, max_length=30), size=6)),
                ('pokemon_base_troca', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, max_length=30), size=6)),
            ],
        ),
    ]
