# Generated by Django 3.1.7 on 2021-03-16 16:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='veredito',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='pokemon_troca',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, max_length=10), size=6), size=1),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='pokemon_user',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, max_length=10), size=6), size=1),
        ),
    ]
