# Generated by Django 3.1.7 on 2021-03-16 16:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210316_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='pokemon_troca',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, max_length=10), size=1), size=6),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='pokemon_user',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, max_length=10), size=1), size=6),
        ),
    ]
