# Generated by Django 3.1.7 on 2021-03-17 15:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pokemon_veredito'),
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonsAnalisados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon_user', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, max_length=10), size=1), size=6)),
                ('pokemon_troca', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, max_length=10), size=1), size=6)),
                ('veredito', models.BooleanField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='PokemonsTrocados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon_user', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, max_length=10), size=1), size=6)),
                ('pokemon_troca', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, max_length=10), size=1), size=6)),
            ],
        ),
        migrations.DeleteModel(
            name='Pokemon',
        ),
    ]
