# Generated by Django 3.1.7 on 2021-03-18 02:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210317_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonsanalisados',
            name='pokemon_troca',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, max_length=10), size=6), size=1),
        ),
        migrations.AlterField(
            model_name='pokemonsanalisados',
            name='pokemon_user',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, max_length=10), size=6), size=1),
        ),
        migrations.AlterField(
            model_name='pokemonstrocados',
            name='pokemon_troca',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, max_length=10), size=6), size=6),
        ),
        migrations.AlterField(
            model_name='pokemonstrocados',
            name='pokemon_user',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, max_length=10), size=6), size=6),
        ),
    ]
